version: 2
jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - run:
          command: echo "test"

  deploy-staging:
    docker:
      - image: debian:stretch
    steps:
      - run:
          command: echo "deploy-staging"

  deploy-production:
    docker:
      - image: debian:stretch
    steps:
      - run:
          command: echo "deploy-production"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /v\d+(\.\d+){0,2}/
      - deploy-staging:
          requires:
            - test
          filters:
            branches:
              only: master
            tags:
              only: /v\d+(\.\d+){0,2}/
      - promote-to-production:
          type: approval
          requires:
            - deploy-staging
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+(\.\d+){0,2}/
      - deploy-production:
          requires:
            - promote-to-production
          filters:
            tags:
              only: /v\d+(\.\d+){0,2}/
